### PR TITLE
fix: Context.add remove nested Tag in dual api

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by tim-smart** [comment]
@mikearnaldi / @IMax153

**Comment by IMax153** [comment]
Nice catch @tim-smart - thanks!

**Review by IMax153 — APPROVED** [review]

**Comment by IMax153** [comment]
Can you go ahead and create a changeset for this? @tim-smart

**Comment by tim-smart** [comment]
> Can you go ahead and create a changeset for this? @tim-smart

Done

**Pull request merged**
